### PR TITLE
Support React 18

### PR DESCRIPTION
**Pull request by ericmorgan1**
Support React version 18.

Problem;
Currently peer dependency will fail when using this in a React 18 project.

### CODE REVIEW

**Comment by ericmorgan1** [comment]
@Aeolun Please take a look if you can

**Comment by Aeolun** [comment]
Sorry, missed this. Let me have a look.

**Comment by Aeolun** [comment]
@all-contributors please add @ericmorgan1 for code

**Comment by ericmorgan1** [comment]
Thanks!

**Pull request merged**
