### PR TITLE
Use passed method to calculate diff

### PR DESCRIPTION
**Pull request by SiebeVE**

### CODE REVIEW

**Comment by oliver-byteboard** [comment]
@Aeolun A merge on this too would be great!

**Comment by Aeolun** [comment]
Could you explain what your use case is here (possibly with an example)? I've yet to find a situation in which anything but char diff makes sense for the line level diff.

**Comment by oliver-byteboard** [comment]
Hi @Aeolun! I believe that without this change, the prop "compareMethod" is not being used at all. I would like to use the diff viewer with "diffWords" so that I can ignore whitespace. Without this PR, we can't change the compareMethod and have it to anything.

**Pull request merged**
